spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda_db
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: camunda-group
      auto-offset-reset: earliest

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    database:
      type: postgres
    deployment-resource-pattern: classpath*:/processes/*.bpmn