server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/credit_db
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Автоматическое обновление схемы
    show-sql: true      # Показывать SQL-запросы в логах
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Диалект PostgreSQL

  kafka:
    bootstrap-servers: localhost:9092  # Kafka сервер

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

jwt:
  secret: "dGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLWp3dC1hdXRoZW50aWNhdGlvbi0xMjM0NTY3OAo="
  expiration: 86400000 # 24 часа